# Generated by Django 5.2.6 on 2025-11-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioComposition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.JSONField(default=dict)),
                ('name', models.JSONField(default=dict)),
            ],
        ),
    ]
