# Generated by Django 5.2.6 on 2025-11-09 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cryptocurrencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OHLCV',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interval', models.CharField(max_length=20)),
                ('open_time', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=10, max_digits=30)),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptocurrencies.cryptocoin')),
            ],
        ),
    ]
